version: 2
jobs:
  build:
    working_directory: ~/clarify-hospital
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
    - image: circleci/node:8.10-stretch-browsers
      environment:
        PGHOST: 0.0.0.0
        DATABASE_URL: "abc"
    steps:
    - restore_cache:
        keys:
        - v1-clarify-source-{{ .Branch }}-{{ .Revision }}

    - checkout

    - save_cache:
        key: v1-clarify-source-{{ .Branch }}-{{ .Revision }}
        paths:
        - ".git"

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

  deploy:
    working_directory: ~/clarify-hospital
    docker:
    - image: circleci/node:8.10-stretch-browsers
    steps:
      - restore_cache:
          keys:
          - v1-clarify-source-{{ .Branch }}-{{ .Revision }}

      - checkout

      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - restore_cache:
          keys:
          - v1-clarify-dep-{{ .Branch }}-{{ checksum "package.json" }}
workflows:
  version: 2
  build-test-deploy:
      jobs:
        - build:
            filters:
              branches:
                # ignore release branches to prevent recursive builds
                ignore: release
        - deploy:
            filters:
              branches:
                only: master
            requires:
              - build
